"""Build an offline four-direction visual review from the generated atlas."""
import base64
from pathlib import Path
p=Path(__file__).resolve().parent
html='''<!doctype html><html lang="ja"><meta charset="utf-8"><title>リナ・方向別レビュー</title><style>body{background:#19262e;color:#e7eded;font:16px system-ui;margin:26px}main{max-width:1040px;margin:auto}p{color:#b4c6c9;line-height:1.7}canvas{background:#293d46;max-width:100%;border-radius:12px}button{padding:9px 18px;margin:0 8px 15px 0;border:1px solid #809b9e;border-radius:6px;background:#344b55;color:white;font:inherit}button.active{background:#d5b580;color:#19262e}</style><main><h1>リナ・方向別の形を確認</h1><p>同じ倍率・同じ接地線で4方向を比較。下段は56px相当の表示です。</p><button data-view="0">正面</button><button data-view="1">右向き</button><button data-view="2">背面</button><button data-view="3">左向き（反転）</button><button id="auto">自動切替：停止中</button><canvas width="1040" height="640"></canvas><p>左側面は右側面の反転による試験表示。非対称の胸の印・髪・ゴーグル金具は別途確認が必要です。<br>これは立ち姿の方向切替です。歩行・武器・回避は含みません。</p></main><script>
const img=new Image();img.src='DATA';const c=document.querySelector('canvas').getContext('2d');let parts=[],selected=0,auto=false;
function crop(x0,x1){let x=Math.round(img.width*x0),w=Math.round(img.width*x1)-x,a=document.createElement('canvas');a.width=w;a.height=img.height;let ac=a.getContext('2d',{willReadFrequently:true});ac.drawImage(img,x,0,w,img.height,0,0,w,img.height);let d=ac.getImageData(0,0,w,a.height).data,l=w,t=a.height,r=0,b=0;for(let y=0;y<a.height;y++)for(let z=0;z<w;z++)if(d[(y*w+z)*4+3]>32){l=Math.min(l,z);r=Math.max(r,z);t=Math.min(t,y);b=Math.max(b,y)}let fl=w,fr=0;for(let y=Math.floor(b-(b-t)*.09);y<=b;y++)for(let z=l;z<=r;z++)if(d[(y*w+z)*4+3]>32){fl=Math.min(fl,z);fr=Math.max(fr,z)}return {x:x+l,y:t,w:r-l+1,h:b-t+1,foot:(fl+fr)/2-l}}
function sprite(view,x,y,scale){let q=parts[view===3?1:view];c.save();c.translate(x,y);if(view===3)c.scale(-1,1);c.drawImage(img,q.x,q.y,q.w,q.h,-q.foot*scale,-q.h*scale,q.w*scale,q.h*scale);c.restore()}
function draw(){if(!parts.length)return;c.clearRect(0,0,1040,640);let scale=56/parts[0].h;for(let n=0;n<4;n++){let x=140+n*250;c.fillStyle='#e7eded';c.font='17px system-ui';c.textAlign='center';c.fillText(['正面','右向き','背面','左向き（反転）'][n],x,35);sprite(n,x,280,scale*4);sprite(n,x,385,scale)}c.strokeStyle='#708e98';for(let y of [280,385]){c.beginPath();c.moveTo(28,y);c.lineTo(1012,y);c.stroke()}c.fillStyle='#e7eded';c.font='14px system-ui';c.fillText('方向切替 / 全方向共通倍率',520,435);sprite(selected,520,610,scale*3);document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',Number(b.dataset.view)===selected))}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.view);draw()});document.querySelector('#auto').onclick=e=>{auto=!auto;e.target.textContent='自動切替：'+(auto?'再生中':'停止中')};setInterval(()=>{if(auto){selected=(selected+1)%4;draw()}},700);img.onload=()=>{parts=[crop(0,.355),crop(.355,.635),crop(.635,1)];draw()};
</script></html>'''
(p/'direction-review.html').write_text(html.replace('DATA','data:image/png;base64,'+base64.b64encode((p/'turnaround.png').read_bytes()).decode()),encoding='utf-8')
