"""Package provisional walking key poses for honest motion review, not game use."""
import base64
from pathlib import Path
p=Path(__file__).resolve().parent
html='''<!doctype html><html lang="ja"><meta charset="utf-8"><title>リナ・歩行ポーズ検証</title><style>body{background:#19262e;color:#e7eded;font:16px system-ui;margin:26px}main{max-width:1040px;margin:auto}p{line-height:1.8;color:#becdd0}canvas{max-width:100%;background:#293d46;border-radius:12px}button{padding:10px 22px;margin:10px;background:#48616b;color:white;border:0;border-radius:6px;font:inherit}.issue{color:#ffd08a}a{color:#ddc39a}</style><main><h1>リナ・短い手足の歩行ポーズ検証</h1><p class="issue">未採用の検証用です。接地と左右の脚の入替が不十分なため、完成した歩行とは扱いません。</p><button id="play">一時停止</button><button id="flip">左向きに反転</button><button id="step">1コマ進める</button><canvas width="1040" height="610"></canvas><p>上段：生成された4姿勢 ／ 下段：仮の連続再生と56px表示。全コマ共通倍率。<br>靴の最低点を揃えただけなので、足裏が接地していることや、移動距離と歩幅の一致を保証しません。</p><a href="direction-review.html">方向別立ち姿の比較へ</a></main><script>
const im=new Image();im.src='DATA';let parts=[],index=0,play=true,flip=false;const c=document.querySelector('canvas').getContext('2d');
function crop(n){let w=Math.floor(im.width/4),x=n*w,a=document.createElement('canvas');a.width=w;a.height=im.height;let ac=a.getContext('2d',{willReadFrequently:true});ac.drawImage(im,x,0,w,im.height,0,0,w,im.height);let d=ac.getImageData(0,0,w,a.height).data,l=w,t=a.height,r=0,b=0;for(let y=0;y<a.height;y++)for(let z=0;z<w;z++)if(d[(y*w+z)*4+3]>32){l=Math.min(l,z);r=Math.max(r,z);t=Math.min(t,y);b=Math.max(b,y)}return {x:x+l,y:t,w:r-l+1,h:b-t+1}}
function sprite(n,x,y,s){let q=parts[n];c.save();c.translate(x,y);if(flip)c.scale(-1,1);c.drawImage(im,q.x,q.y,q.w,q.h,-q.w*s/2,-q.h*s,q.w*s,q.h*s);c.restore()}
function draw(){if(!parts.length)return;c.clearRect(0,0,1040,610);let s=56/parts[0].h;c.fillStyle='#e7eded';c.font='15px system-ui';c.textAlign='center';for(let n=0;n<4;n++){sprite(n,140+n*250,235,s*3);c.fillText('姿勢 '+(n+1),140+n*250,267)}sprite(index,400,555,s*4);sprite(index,740,555,s);c.fillText('仮再生：'+(index+1)+' / 4',400,592);c.fillText('56px',740,592)}
document.querySelector('#play').onclick=e=>{play=!play;e.target.textContent=play?'一時停止':'再生'};document.querySelector('#flip').onclick=e=>{flip=!flip;e.target.textContent=flip?'右向きに戻す':'左向きに反転';draw()};document.querySelector('#step').onclick=()=>{play=false;document.querySelector('#play').textContent='再生';index=(index+1)%4;draw()};im.onload=()=>{parts=[0,1,2,3].map(crop);draw()};setInterval(()=>{if(play){index=(index+1)%4;draw()}},180);
</script></html>'''
(p/'walk-review.html').write_text(html.replace('DATA','data:image/png;base64,'+base64.b64encode((p/'walk-study.png').read_bytes()).decode()),encoding='utf-8')
