import React,{useState} from 'react';
type Asset={id:string;name:string;kind:string;status:string;image:string;image_hash:string;preview:boolean;facts:Record<string,unknown>};
export default function StageBoard({assets,art,onInspect,onPreview,onCompare}:{assets:Asset[];art:(asset:Asset)=>React.ReactNode;onInspect:(id:string)=>void;onPreview:(id:string)=>void;onCompare:(id:string)=>void}){
 const [query,setQuery]=useState(''),[role,setRole]=useState('すべて');
 const stages=assets.filter(a=>a.kind==='ステージ'),rooms=assets.filter(a=>a.kind==='部屋').sort((a,b)=>Number(a.facts.order)-Number(b.facts.order));
 const roles=Array.from(new Set(rooms.map(a=>String(a.facts.role))));
 const matches=(a:Asset)=>`${a.name} ${a.id} ${a.facts.role||''}`.toLowerCase().includes(query.toLowerCase())&&(role==='すべて'||a.facts.role===role);
 const card=(a:Asset)=><article className="stage-card" key={a.id}><button className="stage-art" onClick={()=>onCompare(a.id)} aria-label={`${a.name}を拡大して確認`}>{art(a)}</button><div className="stage-copy"><small>{a.kind==='部屋'?String(a.facts.order).padStart(2,'0'):a.id} · {a.status}</small><h3>{a.name}</h3><p>{String(a.facts.size||'')} <span>{String(a.facts.role||'ステージ定義')}</span></p>{a.facts.connections!=null&&<details><summary>対応する入口の組合せ</summary><p>{String(a.facts.connections)}</p></details>}<div className="stage-actions"><button onClick={()=>onCompare(a.id)} disabled={!a.preview}>拡大・比較</button><button onClick={()=>onPreview(a.id)} disabled={!a.preview}>Godotで確認 ↗</button><button onClick={()=>onInspect(a.id)}>定義・レビュー</button></div></div></article>;
 return <section className="stage-board"><h2>ステージ・部屋一覧</h2><p>ステージ定義 {stages.length}件 / 作り込み部屋 {rooms.length}種類。部屋はストーリーモードの階層（生成版4）とランダム見学で使用します。</p><p className="muted">一覧は保存済み確認画像です。「拡大・比較」「Godotで確認」は現在の定義から描画します。開口の違いは別種類に数えません。</p><div className="filters"><input aria-label="ステージ・部屋を検索" placeholder="部屋名・ID・役割で検索" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="部屋の役割" value={role} onChange={e=>setRole(e.target.value)}>{['すべて',...roles].map(r=><option key={r}>{r}</option>)}</select></div>{role==='すべて'&&<><h3>ステージ定義</h3><div className="stage-grid">{stages.filter(matches).map(card)}</div></>}<h3>作り込み部屋 <small>{rooms.filter(matches).length} / {rooms.length}</small></h3><div className="stage-grid">{rooms.filter(matches).map(card)}</div>{!rooms.filter(matches).length&&<p>条件に一致する部屋がありません。</p>}</section>;
}
